USE IS301
GO 

--CREATING VIEWS
CREATE VIEW PROD_STATS AS 
SELECT  V_CODE,SUM(P_QOH *P_PRICE) AS TOTCOST,
		MAX(P_QOH) AS MAXQTY, MIN(P_QOH) AS MINQTY,
		AVG(P_QOH) AS AVGQTY
FROM	PRODUCT
GROUP BY V_CODE

