-- CREATE TABLES
USE IS301
GO

-- Simple Drops to work on files
DROP TABLE PRODUCT;
DROP TABLE VENDOR;


-- Create Table with Primary Key
CREATE TABLE VENDOR (
V_CODE			INT					NOT NULL UNIQUE,
V_NAME			VARCHAR(35)			NOT NULL,
V_CONTACT		VARCHAR(15)			NOT NULL,
V_AREACODE		CHAR(3)				NOT NULL,
V_PHONE			CHAR(8)				NOT NULL,
V_STATE			CHAR(2)				NOT NULL,
V_ORDER			CHAR(1)				NOT NULL,
PRIMARY KEY (V_CODE)
)

-- Create Table with Primary Key and Foreign Key
CREATE TABLE PRODUCT(
P_CODE		VARCHAR(10)				NOT NULL UNIQUE,
P_DESCRIPT	VARCHAR(35)				NOT NULL,
P_INDATE	DATE					NOT NULL,
P_QOH		SMALLINT				NOT NULL,
P_MIN		SMALLINT				NOT NULL,
P_PRICE		NUMERIC(8,2)			NOT NULL,
P_DISCOUNT	NUMERIC(5,2)			NOT NULL,
V_CODE		INT						NOT NULL,
PRIMARY KEY (P_CODE),
FOREIGN KEY (V_CODE) REFERENCES VENDOR)
