USE NWIND
GO 

PRINT 'This is my Final problems for IS 301 Class'

PRINT 'Code to remove table for problem 5'

BEGIN TRANSACTION
IF OBJECT_ID ('EXAM3_JP', 'U') IS NOT NULL 
DROP TABLE EXAM3_JP;
GO 

PRINT 'PROBLEM 9'
SELECT PRODUCTNAME, CATEGORYNAME, OD.UNITPRICE
FROM CUSTOMERS JOIN ORDERS ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID JOIN [ORDER DETAILS] AS OD ON ORDERS.ORDERID = OD.ORDERID JOIN PRODUCTS ON OD.PRODUCTID = PRODUCTS.PRODUCTID JOIN CATEGORIES ON PRODUCTS.CATEGORYID = CATEGORIES.CATEGORYID
WHERE CUSTOMERS.REGION = 'WA';	
GO
